site_name: Choi Wheatley's Second Brain
site_url: https://ChoiWheatley.github.io
site_author: you
site_description: site_description

nav:
  - About: test.md

theme:
  name: readthedocs
  highlights: true
  hljs_languages:
    - yaml